USE [digital-justice-2023]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Tribunal Member DIM](
	[ID] [int] NOT NULL,
	[Age Range] [varchar](50) NULL,
	[Province] [varchar](10) NULL,
	[Identity] [varchar](100) NULL,
	[Gender identity] [varchar](100) NULL
 CONSTRAINT [PK_Tribunal Member DIM] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


